---
- name: Install and configure DHCP server on Red Hat 9.3
  hosts: your_target_group  # Replace with your host group or specific IP
  become: true

  tasks:
    - name: Install DHCP server package
      ansible.builtin.yum:
        name: dhcp-server
        state: present

    - name: Enable and start the DHCP service
      ansible.builtin.systemd:
        name: dhcpd
        enabled: true
        state: started

    - name: Open DHCP ports in firewall
      ansible.builtin.firewalld:
        port: 
          - 67/udp
          - 68/udp
        permanent: true
        state: enabled
        immediate: true

    - name: Reload firewall to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
